# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rendered_application_spec import RenderedApplicationSpec

class TestRenderedApplicationSpec(unittest.TestCase):
    """RenderedApplicationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderedApplicationSpec:
        """Test RenderedApplicationSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderedApplicationSpec`
        """
        model = RenderedApplicationSpec()
        if include_optional:
            return RenderedApplicationSpec(
                env_vars = {
                    'key' : ''
                    },
                name = '',
                image = ''
            )
        else:
            return RenderedApplicationSpec(
                image = '',
        )
        """

    def testRenderedApplicationSpec(self):
        """Test RenderedApplicationSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
