# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.http_config import HttpConfig

class TestHttpConfig(unittest.TestCase):
    """HttpConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpConfig:
        """Test HttpConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpConfig`
        """
        model = HttpConfig()
        if include_optional:
            return HttpConfig(
                username = '',
                password = '',
                tls_crt = '',
                tls_key = '',
                ca_crt = '',
                skip_server_verification = True,
                token = ''
            )
        else:
            return HttpConfig(
        )
        """

    def testHttpConfig(self):
        """Test HttpConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
