# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.repository_spec import RepositorySpec

class TestRepositorySpec(unittest.TestCase):
    """RepositorySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepositorySpec:
        """Test RepositorySpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepositorySpec`
        """
        model = RepositorySpec()
        if include_optional:
            return RepositorySpec(
                url = '',
                type = 'git',
                http_config = openapi_client.models.http_config.HttpConfig(
                    username = '', 
                    password = '', 
                    tls/crt = '', 
                    tls/key = '', 
                    ca/crt = '', 
                    skip_server_verification = True, 
                    token = '', ),
                validation_suffix = '',
                ssh_config = openapi_client.models.ssh_config.SshConfig(
                    ssh_private_key = '', 
                    private_key_passphrase = '', 
                    skip_server_verification = True, )
            )
        else:
            return RepositorySpec(
                url = '',
                type = 'git',
                http_config = openapi_client.models.http_config.HttpConfig(
                    username = '', 
                    password = '', 
                    tls/crt = '', 
                    tls/key = '', 
                    ca/crt = '', 
                    skip_server_verification = True, 
                    token = '', ),
                ssh_config = openapi_client.models.ssh_config.SshConfig(
                    ssh_private_key = '', 
                    private_key_passphrase = '', 
                    skip_server_verification = True, ),
        )
        """

    def testRepositorySpec(self):
        """Test RepositorySpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
