# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_updated_status_type import DeviceUpdatedStatusType

class TestDeviceUpdatedStatusType(unittest.TestCase):
    """DeviceUpdatedStatusType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceUpdatedStatusType(self):
        """Test DeviceUpdatedStatusType"""
        # inst = DeviceUpdatedStatusType()

if __name__ == '__main__':
    unittest.main()
