# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rollout_policy import RolloutPolicy

class TestRolloutPolicy(unittest.TestCase):
    """RolloutPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RolloutPolicy:
        """Test RolloutPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RolloutPolicy`
        """
        model = RolloutPolicy()
        if include_optional:
            return RolloutPolicy(
                disruption_allowance = openapi_client.models.disruption_allowance.DisruptionAllowance(
                    group_by = [
                        ''
                        ], 
                    min_available = 56, 
                    max_unavailable = 56, ),
                device_selection = openapi_client.models.rollout_device_selection.RolloutDeviceSelection(
                    strategy = '', ),
                success_threshold = '',
                default_update_timeout = '68072888001528021798096225500h'
            )
        else:
            return RolloutPolicy(
        )
        """

    def testRolloutPolicy(self):
        """Test RolloutPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
