# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hook_action_executable import HookActionExecutable

class TestHookActionExecutable(unittest.TestCase):
    """HookActionExecutable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HookActionExecutable:
        """Test HookActionExecutable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HookActionExecutable`
        """
        model = HookActionExecutable()
        if include_optional:
            return HookActionExecutable(
                run = '',
                env_vars = [
                    ''
                    ],
                work_dir = ''
            )
        else:
            return HookActionExecutable(
                run = '',
        )
        """

    def testHookActionExecutable(self):
        """Test HookActionExecutable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
