# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_integrity_status_summary_type import DeviceIntegrityStatusSummaryType

class TestDeviceIntegrityStatusSummaryType(unittest.TestCase):
    """DeviceIntegrityStatusSummaryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceIntegrityStatusSummaryType(self):
        """Test DeviceIntegrityStatusSummaryType"""
        # inst = DeviceIntegrityStatusSummaryType()

if __name__ == '__main__':
    unittest.main()
