# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.certificatesigningrequest_api import CertificatesigningrequestApi


class TestCertificatesigningrequestApi(unittest.TestCase):
    """CertificatesigningrequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CertificatesigningrequestApi()

    def tearDown(self) -> None:
        pass

    def test_create_certificate_signing_request(self) -> None:
        """Test case for create_certificate_signing_request

        """
        pass

    def test_delete_certificate_signing_request(self) -> None:
        """Test case for delete_certificate_signing_request

        """
        pass

    def test_delete_certificate_signing_requests(self) -> None:
        """Test case for delete_certificate_signing_requests

        """
        pass

    def test_list_certificate_signing_requests(self) -> None:
        """Test case for list_certificate_signing_requests

        """
        pass

    def test_patch_certificate_signing_request(self) -> None:
        """Test case for patch_certificate_signing_request

        """
        pass

    def test_read_certificate_signing_request(self) -> None:
        """Test case for read_certificate_signing_request

        """
        pass

    def test_replace_certificate_signing_request(self) -> None:
        """Test case for replace_certificate_signing_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
