# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.http_config_provider_spec import HttpConfigProviderSpec

class TestHttpConfigProviderSpec(unittest.TestCase):
    """HttpConfigProviderSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpConfigProviderSpec:
        """Test HttpConfigProviderSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpConfigProviderSpec`
        """
        model = HttpConfigProviderSpec()
        if include_optional:
            return HttpConfigProviderSpec(
                name = '',
                http_ref = openapi_client.models.http_config_provider_spec_http_ref.HttpConfigProviderSpec_httpRef(
                    repository = '', 
                    suffix = '', 
                    file_path = '', )
            )
        else:
            return HttpConfigProviderSpec(
                name = '',
                http_ref = openapi_client.models.http_config_provider_spec_http_ref.HttpConfigProviderSpec_httpRef(
                    repository = '', 
                    suffix = '', 
                    file_path = '', ),
        )
        """

    def testHttpConfigProviderSpec(self):
        """Test HttpConfigProviderSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
