# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.device_api import DeviceApi


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()

    def tearDown(self) -> None:
        pass

    def test_create_device(self) -> None:
        """Test case for create_device

        """
        pass

    def test_delete_device(self) -> None:
        """Test case for delete_device

        """
        pass

    def test_delete_devices(self) -> None:
        """Test case for delete_devices

        """
        pass

    def test_get_rendered_device_spec(self) -> None:
        """Test case for get_rendered_device_spec

        """
        pass

    def test_list_devices(self) -> None:
        """Test case for list_devices

        """
        pass

    def test_patch_device(self) -> None:
        """Test case for patch_device

        """
        pass

    def test_read_device(self) -> None:
        """Test case for read_device

        """
        pass

    def test_read_device_status(self) -> None:
        """Test case for read_device_status

        """
        pass

    def test_replace_device(self) -> None:
        """Test case for replace_device

        """
        pass

    def test_replace_device_status(self) -> None:
        """Test case for replace_device_status

        """
        pass

    def test_request_console(self) -> None:
        """Test case for request_console

        """
        pass


if __name__ == '__main__':
    unittest.main()
