# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_approve_certificate_signing_request(self) -> None:
        """Test case for approve_certificate_signing_request

        """
        pass

    def test_auth_config(self) -> None:
        """Test case for auth_config

        """
        pass

    def test_auth_validate(self) -> None:
        """Test case for auth_validate

        """
        pass

    def test_deny_certificate_signing_request(self) -> None:
        """Test case for deny_certificate_signing_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
