# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.api.repository_api import RepositoryApi


class TestRepositoryApi(unittest.TestCase):
    """RepositoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepositoryApi()

    def tearDown(self) -> None:
        pass

    def test_create_repository(self) -> None:
        """Test case for create_repository

        """
        pass

    def test_delete_repositories(self) -> None:
        """Test case for delete_repositories

        """
        pass

    def test_delete_repository(self) -> None:
        """Test case for delete_repository

        """
        pass

    def test_list_repositories(self) -> None:
        """Test case for list_repositories

        """
        pass

    def test_patch_repository(self) -> None:
        """Test case for patch_repository

        """
        pass

    def test_read_repository(self) -> None:
        """Test case for read_repository

        """
        pass

    def test_replace_repository(self) -> None:
        """Test case for replace_repository

        """
        pass


if __name__ == '__main__':
    unittest.main()
