# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.certificate_signing_request import CertificateSigningRequest

class TestCertificateSigningRequest(unittest.TestCase):
    """CertificateSigningRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CertificateSigningRequest:
        """Test CertificateSigningRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CertificateSigningRequest`
        """
        model = CertificateSigningRequest()
        if include_optional:
            return CertificateSigningRequest(
                api_version = '',
                kind = '',
                metadata = openapi_client.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = openapi_client.models.certificate_signing_request_spec.CertificateSigningRequestSpec(
                    expiration_seconds = 56, 
                    extra = {
                        'key' : [
                            ''
                            ]
                        }, 
                    request = 'YQ==', 
                    signer_name = '', 
                    uid = '', 
                    usages = [
                        ''
                        ], 
                    username = '', ),
                status = openapi_client.models.certificate_signing_request_status.CertificateSigningRequestStatus(
                    certificate = 'YQ==', 
                    conditions = [
                        null
                        ], )
            )
        else:
            return CertificateSigningRequest(
                api_version = '',
                kind = '',
                metadata = openapi_client.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = openapi_client.models.certificate_signing_request_spec.CertificateSigningRequestSpec(
                    expiration_seconds = 56, 
                    extra = {
                        'key' : [
                            ''
                            ]
                        }, 
                    request = 'YQ==', 
                    signer_name = '', 
                    uid = '', 
                    usages = [
                        ''
                        ], 
                    username = '', ),
        )
        """

    def testCertificateSigningRequest(self):
        """Test CertificateSigningRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
