# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.http_config_provider_spec_http_ref import HttpConfigProviderSpecHttpRef

class TestHttpConfigProviderSpecHttpRef(unittest.TestCase):
    """HttpConfigProviderSpecHttpRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpConfigProviderSpecHttpRef:
        """Test HttpConfigProviderSpecHttpRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpConfigProviderSpecHttpRef`
        """
        model = HttpConfigProviderSpecHttpRef()
        if include_optional:
            return HttpConfigProviderSpecHttpRef(
                repository = '',
                suffix = '',
                file_path = ''
            )
        else:
            return HttpConfigProviderSpecHttpRef(
                repository = '',
                file_path = '',
        )
        """

    def testHttpConfigProviderSpecHttpRef(self):
        """Test HttpConfigProviderSpecHttpRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
