# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.ssh_repo_spec import SshRepoSpec

class TestSshRepoSpec(unittest.TestCase):
    """SshRepoSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SshRepoSpec:
        """Test SshRepoSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SshRepoSpec`
        """
        model = SshRepoSpec()
        if include_optional:
            return SshRepoSpec(
                url = '',
                type = 'git',
                ssh_config = flightctl.models.ssh_config.SshConfig(
                    ssh_private_key = '', 
                    private_key_passphrase = '', 
                    skip_server_verification = True, )
            )
        else:
            return SshRepoSpec(
                url = '',
                type = 'git',
                ssh_config = flightctl.models.ssh_config.SshConfig(
                    ssh_private_key = '', 
                    private_key_passphrase = '', 
                    skip_server_verification = True, ),
        )
        """

    def testSshRepoSpec(self):
        """Test SshRepoSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
