# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.rendered_device_spec_systemd import RenderedDeviceSpecSystemd

class TestRenderedDeviceSpecSystemd(unittest.TestCase):
    """RenderedDeviceSpecSystemd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderedDeviceSpecSystemd:
        """Test RenderedDeviceSpecSystemd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderedDeviceSpecSystemd`
        """
        model = RenderedDeviceSpecSystemd()
        if include_optional:
            return RenderedDeviceSpecSystemd(
                match_patterns = [
                    ''
                    ]
            )
        else:
            return RenderedDeviceSpecSystemd(
        )
        """

    def testRenderedDeviceSpecSystemd(self):
        """Test RenderedDeviceSpecSystemd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
