# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sort_order import SortOrder

class TestSortOrder(unittest.TestCase):
    """SortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortOrder(self):
        """Test SortOrder"""
        # inst = SortOrder()

if __name__ == '__main__':
    unittest.main()
