# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_lifecycle_hook_type import DeviceLifecycleHookType

class TestDeviceLifecycleHookType(unittest.TestCase):
    """DeviceLifecycleHookType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceLifecycleHookType(self):
        """Test DeviceLifecycleHookType"""
        # inst = DeviceLifecycleHookType()

if __name__ == '__main__':
    unittest.main()
