# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.api.enrollmentrequest_api import EnrollmentrequestApi


class TestEnrollmentrequestApi(unittest.TestCase):
    """EnrollmentrequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollmentrequestApi()

    def tearDown(self) -> None:
        pass

    def test_approve_enrollment_request(self) -> None:
        """Test case for approve_enrollment_request

        """
        pass

    def test_create_enrollment_request(self) -> None:
        """Test case for create_enrollment_request

        """
        pass

    def test_delete_enrollment_request(self) -> None:
        """Test case for delete_enrollment_request

        """
        pass

    def test_delete_enrollment_requests(self) -> None:
        """Test case for delete_enrollment_requests

        """
        pass

    def test_list_enrollment_requests(self) -> None:
        """Test case for list_enrollment_requests

        """
        pass

    def test_read_enrollment_request(self) -> None:
        """Test case for read_enrollment_request

        """
        pass

    def test_read_enrollment_request_status(self) -> None:
        """Test case for read_enrollment_request_status

        """
        pass

    def test_replace_enrollment_request(self) -> None:
        """Test case for replace_enrollment_request

        """
        pass

    def test_replace_enrollment_request_status(self) -> None:
        """Test case for replace_enrollment_request_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
