# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.condition_status import ConditionStatus

class TestConditionStatus(unittest.TestCase):
    """ConditionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionStatus(self):
        """Test ConditionStatus"""
        # inst = ConditionStatus()

if __name__ == '__main__':
    unittest.main()
