# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.match_expression import MatchExpression

class TestMatchExpression(unittest.TestCase):
    """MatchExpression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchExpression:
        """Test MatchExpression
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchExpression`
        """
        model = MatchExpression()
        if include_optional:
            return MatchExpression(
                key = '',
                operator = 'In',
                values = [
                    ''
                    ]
            )
        else:
            return MatchExpression(
                key = '',
                operator = 'In',
        )
        """

    def testMatchExpression(self):
        """Test MatchExpression"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
