# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.resourcesync_api import ResourcesyncApi


class TestResourcesyncApi(unittest.TestCase):
    """ResourcesyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourcesyncApi()

    def tearDown(self) -> None:
        pass

    def test_create_resource_sync(self) -> None:
        """Test case for create_resource_sync

        """
        pass

    def test_delete_resource_sync(self) -> None:
        """Test case for delete_resource_sync

        """
        pass

    def test_delete_resource_syncs(self) -> None:
        """Test case for delete_resource_syncs

        """
        pass

    def test_list_resource_sync(self) -> None:
        """Test case for list_resource_sync

        """
        pass

    def test_patch_resource_sync(self) -> None:
        """Test case for patch_resource_sync

        """
        pass

    def test_read_resource_sync(self) -> None:
        """Test case for read_resource_sync

        """
        pass

    def test_replace_resource_sync(self) -> None:
        """Test case for replace_resource_sync

        """
        pass


if __name__ == '__main__':
    unittest.main()
