# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_update_policy_spec import DeviceUpdatePolicySpec

class TestDeviceUpdatePolicySpec(unittest.TestCase):
    """DeviceUpdatePolicySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceUpdatePolicySpec:
        """Test DeviceUpdatePolicySpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceUpdatePolicySpec`
        """
        model = DeviceUpdatePolicySpec()
        if include_optional:
            return DeviceUpdatePolicySpec(
                download_schedule = flightctl.models.update_schedule.UpdateSchedule(
                    time_zone = 'Local', 
                    at = '', 
                    start_grace_duration = '0s', ),
                update_schedule = flightctl.models.update_schedule.UpdateSchedule(
                    time_zone = 'Local', 
                    at = '', 
                    start_grace_duration = '0s', )
            )
        else:
            return DeviceUpdatePolicySpec(
        )
        """

    def testDeviceUpdatePolicySpec(self):
        """Test DeviceUpdatePolicySpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
