# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.templateversion_api import TemplateversionApi


class TestTemplateversionApi(unittest.TestCase):
    """TemplateversionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplateversionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_template_version(self) -> None:
        """Test case for delete_template_version

        """
        pass

    def test_delete_template_versions(self) -> None:
        """Test case for delete_template_versions

        """
        pass

    def test_list_template_versions(self) -> None:
        """Test case for list_template_versions

        """
        pass

    def test_read_template_version(self) -> None:
        """Test case for read_template_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
