# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.enrollmentconfig_api import EnrollmentconfigApi


class TestEnrollmentconfigApi(unittest.TestCase):
    """EnrollmentconfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollmentconfigApi()

    def tearDown(self) -> None:
        pass

    def test_enrollment_config(self) -> None:
        """Test case for enrollment_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
